services:
  # 공통 설정을 재사용하기 위한 정의 (Anchor)
  mysql-common: &mysql-common
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: products
      TZ: Asia/Seoul
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d # 초기 테이블 생성 SQL 실행

  mysql-0:
    <<: *mysql-common
    container_name: mysql-3306
    ports:
      - "3308:3306"

  mysql-1:
    <<: *mysql-common
    container_name: mysql-3307
    ports:
      - "3309:3306"

  mysql-2:
    <<: *mysql-common
    container_name: mysql-3308
    ports:
      - "3310:3306"

networks:
  default:
    name: sharding-network
