spring:
  datasource:
    url: jdbc:mysql://localhost:3306/notifications?rewriteBatchedStatements=true&profileSQL=false&logger=Slf4JLogger
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
